development:
  adapter: postgresql
  database: santa_bot_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: santa_bot_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: santa_bot_production
  pool: 5
  timeout: 5000
